# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App de Ingressos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App de Ingressos
  
  pod 'CPF-CNPJ-Validator'
  pod 'Alamofire'
  pod 'CreditCardValidator'
  
end
